version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - notification-mongo

  notification-mongo:
    image: mongo:7
    ports:
      - "27021:27017"
    environment:
      - MONGO_INITDB_DATABASE=notification_db
    volumes:
      - notification_data:/data/db

volumes:
  notification_data: