

services:
  auth-service:
    build: .
    ports:
      - "3001:3001"
    environment:
     - JWT_SECRET=un_secreto_muy_fuerte_y_unico  # 🔥 Definido aquí
     - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth_db
    volumes:
      - auth_data:/data/db

volumes:
  auth_data:
