version: '3.8'
services:
  bid-service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - JWT_SECRET=un_secreto_muy_fuerte_y_unico  # 🔥 Definido aquí
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - bid-mongo

  bid-mongo:
    image: mongo:7
    ports:
      - "27020:27017"  # Cambiado de 27018 a 27019 para evitar conflicto
    volumes:
      - bid_data:/data/db

volumes:
  bid_data: